version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

  app:
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MARVEL_ENDPOINT=
      - ts=
      - MARVEL_API_KEY=
      - MARVEL_PRIVATE_KEY=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command:
      sh -c 'yarn && yarn dev'